version: 0.2

phases:
  install:
    commands:
    - echo Installing node...
    - curl -sL https://deb.nodesource.com/setup_12.x | bash -
    - apt install -y nodejs
  pre_build:
    commands:
    - echo Installing dependencies...
    - npm install
  build:
    commands:
    - echo Running tests...
    - npm test
    - echo Building...
    - npm npm run-script build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist